### ISSUE TITLE
A strange command to append a event...

### ISSUE THREAD

**Issue by Corrado-LR2** [Tristimdorion/Lab-Rats-2#10]
File "game/game_roles/role_sister.rpy", line 109, in add_sister_instathot_mom_report_action
    person.on_talk_event_list.append(sister_instathot_mom_report_crisis)
AttributeError: 'NoneType' object has no attribute 'on_talk_event_list'

Shouldn't this be: "mc.business.mandatory_crises_list.append(sister_instathot_mom_report_crisis)" ?

**Comment by Tristimdorion** [comment]
Looks good to me...

**Comment by Corrado-LR2** [comment]
IDK, in 0.32.3 I got that error, in 0.33.3 I don't...
