### ISSUE TITLE
role_aunt.rpy line 571 should be removed

### ISSUE THREAD

**Issue by Corrado-LR2** [Tristimdorion/Lab-Rats-2#12]
I think line 570 generate the correct storyline, and line 571 it's just unusefull...
Can you double-check to be sure ? (be carefull with the '_at' in the names, damn Vren !)
![Corel](https://user-images.githubusercontent.com/71410408/94689590-59362900-032f-11eb-8347-d86d1e939421.jpg)

**Comment by Tristimdorion** [comment]
Is this still an issue? Please elaborate...

**Comment by Corrado-LR2** [comment]
No, it has been fixed. Lines are now 620 and 621 (empty).
