### ISSUE TITLE
Wants creampie def

### ISSUE THREAD

**Issue by Badrabbit-LR2** [Tristimdorion/Lab-Rats-2#14]
script.rpy at 3091:
                effective_slut += 10 - (10 * the_person.get_opinion_score("incest"))
relates to family members. Increasing the effective sluttiness makes them want creampie more. A positive incest probably should correlate with wanting creampie more. Also family probably should start off as less likely to want a creampie generally. So I think that it probably should be:
                effective_slut += -10 + (10 * the_person.get_opinion_score("incest"))

**Comment by Tristimdorion** [comment]
If the eff_slut is lowered, she is is more willing to creampie, so I think the code is correct.
