### ISSUE TITLE
Not an issue but an improvement...

### ISSUE THREAD

**Issue by Corrado-LR2** [Tristimdorion/Lab-Rats-2#18]
Since the new scheduling system allow to set different schedules for the days of the week, the University people (Nora, Lily, Erica and Emily) shouldn't be scheduled somewhere else during the weekend ?

**Comment by Tristimdorion** [comment]
I've changed their schedules, so that they do study on Saturday (maybe library or study group) during the day (sat evening and sundays off), for Erica, she is part of the mod, but she also has a different schedule now, she is in the gym on sat and sun during the day with evenings off.
