### ISSUE TITLE
script.rpy line 3195

### ISSUE THREAD

**Issue by Corrado-LR2** [Tristimdorion/Lab-Rats-2#20]
I think this line 3195: effective_slut = the_person.effective_sluttiness("creampie") + (10*the_person.get_opinion_score("creampies"))
should be: effective_slut = the_person.effective_sluttiness() + (10*the_person.get_opinion_score("creampies"))

**Comment by Tristimdorion** [comment]
The problem is using the_person instead of self in the function. Has been fixed.
