### ISSUE TITLE
Taxes Crisis wetness isn't resetting

### ISSUE THREAD

**Issue by Bungzi** [Tristimdorion/Lab-Rats-2#21]
I've done the taxes crisis several times now and the black jacket is what is getting wet and the color black seems to not be being reset. At this point all the black in all of my outfits is at .31 transparency pants, shirts, jackets. I did check after my last taxes crisis and the transparency was lower on a different outfit. 

Not sure if it's something in your code or not but this wasn't happening that I noticed in the non modded 0.34.2 update or the 0.33.6 modded version I've played recently.

**Comment by Tristimdorion** [comment]
Uploaded a fix.
