### ISSUE TITLE
OpenGL crash on MacOS "BigSur" 11.0

### ISSUE THREAD

**Issue by ShivaThomas** [Tristimdorion/Lab-Rats-2#24]
Hello!  JeanLeBon, on F95, found how to solve the game crashing on launch when on MacOS "Big Sur" 11.0.
The file _Lab_Rats_2.app/Contents/Resources/autorun/game/OpenGL/platform/darwin.py_ need to be updated.
Line 37 should be changed from 'OpenGL' to '/System/Library/Frameworks/OpenGL.framework/Versions/Current/OpenGL'
I've tested the fix and it solve the issue.

**Comment by Tristimdorion** [comment]
Since the OpenGL is no longer referenced this is now obsolete.

**Comment by ShivaThomas** [comment]
Thank you. You're right, the problem is no more. ^_^
