### ISSUE TITLE
Two menus when giving command

### ISSUE THREAD

**Issue by FranticMan** [Tristimdorion/Lab-Rats-2#26]
I presume there's a double definition of the menus in **chat_actions.rpy** in line 994 and 1019.
After giving a girl a command first honeycomb style menu shows (without any function), after choosing any option a second menu is shown (top down list style).

Suggested fix:
On my research line 1031 causes showing the first menu. After comment the line with a #, it seems fixed.
`#$ player_choice = call_formated_action_choice([change_titles_action, wardrobe_change_action, serum_demand_action, strip_demand_action, touch_demand_action, bc_demand_action, "Return"])`
And line 1033 needs to be uncommented:
`$ player_choice = _return`

**Comment by Tristimdorion** [comment]
This was a merge issue, this has been resolved.
