### ISSUE TITLE
After husband is coming and continuing

### ISSUE THREAD

**Issue by FranticMan** [Tristimdorion/Lab-Rats-2#27]
**role_affair.rpy**, line 339 causes an exception because of its parameter.

Suggestef fix:
In file **sex_mechanics.rpy**
line 1: parameter "_skip_condom = True_" is missing.
`label fuck_person(the_person, private = True, start_position = None, start_object = None, skip_intro = False, girl_in_charge = False, self_strip = True, hide_leave = False, position_locked = False, report_log = None, affair_ask_after = True, ignore_taboo = False, skip_condom = True):`

**Comment by Tristimdorion** [comment]
Fixed: skip_condom is not a parameter of fuck_person.
