### ISSUE TITLE
Function find_in_list is missing

### ISSUE THREAD

**Issue by FranticMan** [Tristimdorion/Lab-Rats-2#34]
At the point of starting the game an exception occurred because the definition of the new function find_in_list is missing.
I already made a suggestion how it should look like.

In the MODS release in /game/Mods/Core/Mechanics/Helper_Functions/list_functions.rpy is a definition.
Should be moved to the vanilla version.

**Comment by Tristimdorion** [comment]
The find_in_list have been removed and rewritten to simple python statements.
