### ISSUE TITLE
Is "def wants_creampie(self):" in script.rpy works as intended ?

### ISSUE THREAD

**Issue by 0Vavilon0** [Tristimdorion/Lab-Rats-2#42]
For True - `effective_slut >= creampie_threshold`. Each **"if"** should check if she is more willing for it and add some amount to "effective_slut". Or am I wrong ?

1. `on_birth_control` - should be just `20`, instead of `-20`
2. `affair_role` =  `5 + (10 * self.get_opinion_score("cheating on men"))`
negative increase on positive opinion(**opinion problem**) on "cheating on men"
3. `relationship != "Single"` =  `-15 + (10 * self.get_opinion_score("cheating on men"))` 
15 is negative for `# Less likely to want to be creampied if she's in a relationship` and + for opinion problem
4. `girlfriend_role` =  `10 + (5*self.get_opinion_score("being submissive"))` 
If opinion is 2, then it adds -20 to "effective_slut"
5. `is_family` =  `-10 + (10 * self.get_opinion_score("incest"))`
Incest is bad and again opinion problem

**Comment by Tristimdorion** [comment]
Good spot, see attached commit has solution.
