### ISSUE TITLE
Error on toxic serum expire when character is in a different area

### ISSUE THREAD

**Issue by Saukendar** [Tristimdorion/Lab-Rats-2#54]
[error.txt](https://github.com/Tristimdorion/Lab-Rats-2/files/6810283/error.txt)

Error is consistent and repeatable, repeats on every time unit advance as long as you aren't in area with effected character. 
UI reports negative serum duration when you go to area where character is.
Error clears when you allow time unit advance and you are in area with effected character.

**Comment by Tristimdorion** [comment]
Issue has been resolved a while back.
