### ISSUE TITLE
Action: "Cousin boob job get" failed - NameError: name 'the_day' is not defined

### ISSUE THREAD

**Issue by Saukendar** [Tristimdorion/Lab-Rats-2#55]
[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 212, in script call
    $ talk_action.call_action(picked_option)
  File "game/game_roles/role_cousin.rpy", line 874, in script
    python: #Sets up an event that will trigger after a set number of days when she has gotten her boob job. This event, in turns, adds in an event when you talk to her.
  File "game/game_roles/role_cousin.rpy", line 876, in <module>
    cousin_boobjob_get_action = Action("Cousin boob job get", cousin_boobjob_get_requirement, "cousin_boobjob_get_label", args = the_person, requirement_args = [the_person, the_day + renpy.random.randint(4,6)])
NameError: name 'the_day' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 212, in script call
    $ talk_action.call_action(picked_option)
  File "game/game_roles/role_cousin.rpy", line 874, in script
    python: #Sets up an event that will trigger after a set number of days when she has gotten her boob job. This event, in turns, adds in an event when you talk to her.
  File "renpy/ast.py", line 934, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2218, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/game_roles/role_cousin.rpy", line 876, in <module>
    cousin_boobjob_get_action = Action("Cousin boob job get", cousin_boobjob_get_requirement, "cousin_boobjob_get_label", args = the_person, requirement_args = [the_person, the_day + renpy.random.randint(4,6)])
NameError: name 'the_day' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.5.1648
Lab Rats 2 - Down to Business v0.42.1
Thu Jul 15 10:33:57 2021
[/code]

**Comment by Tristimdorion** [comment]
Are you using the correct branch? The master branch is the original code from VREN, the bugfix branch contains the fixes, previous releases of the fixes can be found in the release history.
