### ISSUE TITLE
Human Breeding Hormones breast shrinkage

### ISSUE THREAD

**Issue by Anulithic** [Tristimdorion/Lab-Rats-2#6]
Girls with F or FF-cup breasts will shrink down to E after the Human Breeding Hormones effect ends, since it's implemented just by growing them 2 sizes on start and shrinking 2 sizes on end. Not sure exactly how to get around that cleanly.

**Comment by Tristimdorion** [comment]
I'll wait for the next version, if it's still an issue I will have a look.
