### ISSUE TITLE
Opinions in conditions for insta / only-fans / dikdok acounts (bf02bf7)

### ISSUE THREAD

**Issue by 0Vavilon0** [Tristimdorion/Lab-Rats-2#67]
"showing her ass" opinion in dikdok and all other opinions in onlyfans should have minuses.

**Comment by Tristimdorion** [comment]
Please elaborate, filename / line number.

**Comment by 0Vavilon0** [comment]
bf02bf773a786e2676b4a4b886fc42e6b605d3d4
game/crises/limited_time_crises/general_LTE.rpy
