### ISSUE TITLE
sister taboo quest issues

### ISSUE THREAD

**Issue by Blabert** [Tristimdorion/Lab-Rats-2#73]
Hi,

that quest is broken in several parts:

1:
change_serum(-10) is called at the beginning and for no_effect serums change_serum(-9)
Should probably be +9

https://github.com/Tristimdorion/Lab-Rats-2/blob/6284cde7493f3fba682bd21621dc85a1abbd0f05/game/game_roles/role_sister/role_sister_taboo_quests.rpy#L697

https://github.com/Tristimdorion/Lab-Rats-2/blob/6284cde7493f3fba682bd21621dc85a1abbd0f05/game/game_roles/role_sister/role_sister_taboo_quests.rpy#L860

2:
Test persons serum stat changes are still logged.

3:
SerumInventory get_serum_count() is broken (object to string comparison) and will keep the button disabled

https://github.com/Tristimdorion/Lab-Rats-2/blob/6284cde7493f3fba682bd21621dc85a1abbd0f05/game/major_game_classes/serum_related/SerumInventory.rpy#L11

I'd propose to change it to 'if design == serum_design:'

Edit:
This will break your business inventory however, so new proposal:
get_max_serum_count()
 if self.get_serum_count(design[0]) > highest_count:
                    highest_count = self.get_serum_count(design[0])
End Edit

4:
VJ taboo action is appended more than once

https://github.com/Tristimdorion/Lab-Rats-2/blob/6284cde7493f3fba682bd21621dc85a1abbd0f05/game/game_roles/role_sister/role_sister_taboo_quests.rpy#L642

5:
Oral quest action is not showing up

https://github.com/Tristimdorion/Lab-Rats-2/blob/6284cde7493f3fba682bd21621dc85a1abbd0f05/game/game_roles/role_sister/role_sister_taboo_quests.rpy#L283

**Comment by Tristimdorion** [comment]
I think I solved them all in commits #2c47c7c, #d53d2d2 and #13a0b40
