### ISSUE TITLE
Odd path

### ISSUE THREAD

**Issue by Saukendar** [Tristimdorion/Lab-Rats-2#88]
Employ Mom
Mom presents daughter as employee candidate (new sister - sort of)
Hire the new daughter
Taker new daughter to movies
Result is "Mom's bedroom" appears under visit someone, but can't be accessed
![visit](https://user-images.githubusercontent.com/3802135/154819463-0e4f10bc-49dd-4d60-b0d8-006c1fc7f5d5.png)

**Comment by Tristimdorion** [comment]
This is resolved in the mod only, VREN can figure this one out :)
