### ISSUE TITLE
Another odd path

### ISSUE THREAD

**Issue by Saukendar** [Tristimdorion/Lab-Rats-2#90]
Find Mrs. Vandenberg in town before opening "University Campus"
Taker her to the movies and go home with her
When you "Offer to tutor her at home." Emily you get duplicate Emily's home
![visit2](https://user-images.githubusercontent.com/3802135/154819962-3e3bc7ab-f39a-4c38-91d7-5b604081bfbb.png)

**Comment by Tristimdorion** [comment]
She shouldn't appear in Town anymore, prior to intro.
