### ISSUE TITLE
Display issue on weaken opinion

### ISSUE THREAD

**Issue by Saukendar** [Tristimdorion/Lab-Rats-2#91]
"Likes" show as "Loves" 
Actual action works fine
![Becky-op](https://user-images.githubusercontent.com/3802135/155521696-83c210fe-78da-4e8c-a002-2bc83d38bd75.png)
![Becky-weaken](https://user-images.githubusercontent.com/3802135/155521713-d56be6fd-2ec4-40eb-af52-d3e958046796.png)

Edit: looks like "Dislikes" also shows as "Hates"

**Comment by Tristimdorion** [comment]
I think you did not download the correct branch, the 'master' branch is the original code from VREN, the 'bugfix' branch contains the actual changes.
