### ISSUE TITLE
Emily - duplicate "Tutor her." actions

### ISSUE THREAD

**Issue by Saukendar** [Tristimdorion/Lab-Rats-2#92]
![Emily-tutor](https://user-images.githubusercontent.com/3802135/155524590-acfd7589-f71b-4fed-8d19-179bf0287ce4.png)

**Comment by Tristimdorion** [comment]
I think you did not download the correct branch, the 'master' branch is the original code from VREN, the 'bugfix' branch contains the actual changes.
