### ISSUE TITLE
Displpay issue - Steph pushes coworker to suck

### ISSUE THREAD

**Issue by Saukendar** [Tristimdorion/Lab-Rats-2#93]
When you pass by the break room you overhear...
Display option is "Let Steph give you a blowjob" - actually it's the coworker...
![Display-issue0](https://user-images.githubusercontent.com/3802135/155591246-a32ed0e3-8e60-4ab5-9778-9eed457c5fea.png)
![Display-issue](https://user-images.githubusercontent.com/3802135/155591263-4d899dd8-1aaa-4a9e-b228-cd2f3fe92a29.png)

**Comment by Tristimdorion** [comment]
I think you did not download the correct branch, the 'master' branch is the original code from VREN, the 'bugfix' branch contains the actual changes.
