### ISSUE TITLE
No use for points when Goals are complete

### ISSUE THREAD

**Issue by Saukendar** [Tristimdorion/Lab-Rats-2#94]
There should be some use for points when Goals are complete, maybe exchange for Energy?
![Issue](https://user-images.githubusercontent.com/3802135/155631830-18baa6b6-9dd8-4911-a4c5-f8499953ba97.png)

**Comment by Tristimdorion** [comment]
Take this up with the original creator of the game, I'm not introducing new mechanics in the bugfix.
