### ISSUE TITLE
Display issue - Visit alignment

### ISSUE THREAD

**Issue by Saukendar** [Tristimdorion/Lab-Rats-2#95]
Target placement starts well off the left side.
More to the point, there is a gap under the top left most target
![visit](https://user-images.githubusercontent.com/3802135/155738440-0d674e9a-1551-4ff7-a0fa-392c72f05ad3.png)

**Comment by Tristimdorion** [comment]
I think you did not download the correct branch, the 'master' branch is the original code from VREN, the 'bugfix' branch contains the actual changes.

**Comment by Saukendar** [comment]
I'm reporting as per a UI based QA without reference to the code
